import type { DeepReport } from "../data/deepReport";

export function buildAgentStarterPrompt(report: DeepReport): string {
  return [
    "你是一位資深全端工程師與產品工程師。",
    "",
    "請根據以下規格建立 MVP。",
    "",
    "要求：",
    "",
    "- 優先使用 React + Vite",
    "- 優先使用 Cloudflare Pages",
    "- 保持架構簡單",
    "- 避免過度設計",
    "- 不要加入未被要求的功能",
    "- 不要新增會員系統",
    "- 不要新增資料庫",
    "- 不要新增金流",
    "",
    "請先完成 MVP，再考慮擴充功能。",
    "",
    "## 產品目標",
    report.agentMvpKit.productGoal,
    "",
    "## 目標客群",
    report.agentMvpKit.targetAudience,
    "",
    "## MVP 功能需求",
    formatList(report.agentMvpKit.mvpRequirements),
    "",
    "## 頁面需求",
    formatList(report.agentMvpKit.pageRequirements),
    "",
    "## UI 需求",
    formatList(report.agentMvpKit.uiRequirements),
    "",
    "## 資料結構",
    formatList(report.agentMvpKit.dataStructure),
    "",
    "## 技術限制",
    formatList(report.agentMvpKit.technicalConstraints),
    "",
    "## 建議檔案結構",
    formatList(report.agentDevelopmentKit.suggestedFileStructure),
    "",
    "## 開發任務拆解",
    formatList([
      ...report.agentDevelopmentKit.implementationSteps,
      ...(report.agentExecutionStrategy?.buildOrder ?? []),
    ]),
    "",
    "## 驗收條件",
    formatList([
      ...report.agentMvpKit.acceptanceCriteria,
      ...(report.agentExecutionStrategy?.mvpDoneCriteria ?? []),
    ]),
    "",
    "## MVP 瘦身方案",
    report.mvpReduction.sevenDayScope,
    "",
    "## 保留功能",
    formatList(report.mvpReduction.keep),
    "",
    "## 不要做的功能",
    formatList([
      ...report.mvpReduction.remove,
      ...report.mvpFeatures.notRecommended,
    ]),
    "",
    "## 補充開發 Brief",
    report.agentDevelopmentKit.copyPasteAgentBrief,
  ]
    .join("\n");
}

function formatList(items: string[]): string {
  return items.map((item) => `- ${item}`).join("\n");
}
