export function buildAgentStarterPrompt(report) {
    return [
        "你是一位資深全端工程師與產品工程師。",
        "",
        "請根據以下規格建立 MVP。",
        "",
        "要求：",
        "",
        "- 優先使用 React + Vite",
        "- 優先使用 Cloudflare Pages",
        "- 保持架構簡單",
        "- 避免過度設計",
        "- 不要加入未被要求的功能",
        "- 不要新增會員系統",
        "- 不要新增資料庫",
        "- 不要新增金流",
        "",
        "請先完成 MVP，再考慮擴充功能。",
        "",
        "# 第三方服務與外部整合規則",
        "",
        "若產品需要使用以下服務：",
        "",
        "- 金流",
        "- 外部 API",
        "- Email",
        "- 會員系統",
        "- 資料庫",
        "- 第三方 SaaS",
        "- OAuth 登入",
        "- 雲端儲存",
        "- 推播服務",
        "- AI 模型服務",
        "",
        "第一版 MVP 請不要進行正式串接。",
        "",
        "目標：先完成產品框架與操作流程驗證。",
        "",
        "## 必須完成",
        "",
        "### 1. 建立功能框架",
        "",
        "完成 UI、頁面流程與使用者操作流程，讓使用者可以完整預覽產品運作方式。",
        "",
        "### 2. 建立 Mock Function",
        "",
        "若需要第三方服務，請先建立 mockPayment()、mockEmailSend()、mockGenerateReport()、mockUserLogin() 或等效模擬流程。",
        "",
        "確保即使沒有第三方服務，產品仍可正常展示與測試。",
        "",
        "### 3. 建立 Placeholder",
        "",
        "請在對應位置留下 TODO，例如：",
        "",
        "- TODO: Replace with Stripe API",
        "- TODO: Replace with Gemini API",
        "- TODO: Replace with Resend API",
        "",
        "### 4. 建立 .env.example",
        "",
        "若產品涉及第三方服務，必須建立 .env.example，僅保留範例，禁止填入真實金鑰。",
        "",
        "範例：",
        "",
        "# Gemini",
        "VITE_GEMINI_API_KEY=",
        "",
        "# Stripe",
        "STRIPE_SECRET_KEY=",
        "VITE_STRIPE_PUBLISHABLE_KEY=",
        "",
        "# Resend",
        "RESEND_API_KEY=",
        "",
        "### 5. 建立 README 設定說明",
        "",
        "README 必須包含啟動步驟、環境變數設定、第三方服務設定方式與部署方式，讓非工程師也能完成設定。",
        "",
        "### 6. 建立待使用者設定項目",
        "",
        "README 或專案文件中必須新增「待使用者設定項目」，每一項使用以下格式：",
        "",
        "用途：",
        "設定位置：",
        "環境變數名稱：",
        "取得方式：",
        "是否必填：",
        "",
        "範例：",
        "",
        "用途：AI 報告生成",
        "設定位置：.env.local",
        "環境變數名稱：VITE_GEMINI_API_KEY",
        "取得方式：Google AI Studio",
        "是否必填：是",
        "",
        "## 必須保證",
        "",
        "即使 API Key 為空、Stripe 未設定、資料庫不存在、Email 未設定，專案仍可 npm install、npm run dev 正常啟動，並可展示完整 MVP 流程。",
        "",
        "## 禁止事項",
        "",
        "- 禁止寫死 API Key",
        "- 禁止建立正式付款流程",
        "- 禁止強制登入",
        "- 禁止建立正式資料庫架構",
        "- 禁止要求使用者先申請第三方服務才能啟動專案",
        "- 禁止因缺少第三方服務導致專案無法啟動",
        "- 禁止自動產生真實金鑰",
        "",
        "## 開發原則",
        "",
        "優先做到可展示、可驗證、可部署、可操作，之後再進行正式串接。",
        "",
        "## 產品目標",
        report.agentMvpKit.productGoal,
        "",
        "## 目標客群",
        report.agentMvpKit.targetAudience,
        "",
        "## MVP 功能需求",
        formatList(report.agentMvpKit.mvpRequirements),
        "",
        "## 頁面需求",
        formatList(report.agentMvpKit.pageRequirements),
        "",
        "## UI 需求",
        formatList(report.agentMvpKit.uiRequirements),
        "",
        "## 資料結構",
        formatList(report.agentMvpKit.dataStructure),
        "",
        "## 技術限制",
        formatList(report.agentMvpKit.technicalConstraints),
        "",
        "## 建議檔案結構",
        formatList(report.agentDevelopmentKit.suggestedFileStructure),
        "",
        "## 開發任務拆解",
        formatList([
            ...report.agentDevelopmentKit.implementationSteps,
            ...(report.agentExecutionStrategy?.buildOrder ?? []),
        ]),
        "",
        "## 驗收條件",
        formatList([
            ...report.agentMvpKit.acceptanceCriteria,
            ...(report.agentExecutionStrategy?.mvpDoneCriteria ?? []),
        ]),
        "",
        "## MVP 瘦身方案",
        report.mvpReduction.sevenDayScope,
        "",
        "## 保留功能",
        formatList(report.mvpReduction.keep),
        "",
        "## 不要做的功能",
        formatList([
            ...report.mvpReduction.remove,
            ...report.mvpFeatures.notRecommended,
        ]),
        "",
        "## 補充開發 Brief",
        report.agentDevelopmentKit.copyPasteAgentBrief,
    ]
        .join("\n");
}
function formatList(items) {
    return items.map((item) => `- ${item}`).join("\n");
}
